name: dart_task_cli
description: Une application en ligne de commande pour gérer les tâches en Dart.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^6.1.0
  test: ^1.25.0